 spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jpatest?characterEncoding=UTF-8&&useSSL=true
    username: root
    password:

    filters: stat,wall,log4j
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    poolPreparedStatement: true
    maxPoolPreparedStatementPerConnections: 20

    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    timeBetweenEvictionRunsMills: 60000
    minEvictableIdeleTimeMills: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false


  jpa:
    hibernate:
      ddl-auto: update
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    database: mysql

  mvc:
    view:
      prefix: /webapp/WEB-INF/jsp/
      suffix: .jsp